# AI Callcenter Agent - Development Override
# Designer: Abdullah Alawiss
# This file provides development-specific settings

version: '3.8'

services:
  # Development overrides for backend
  backend:
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - ./data/sample_calls:/app/sample_calls
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug
      - ENVIRONMENT=development
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Development overrides for celery worker
  celery-worker:
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - ./data/sample_calls:/app/sample_calls
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug
      - ENVIRONMENT=development

  # Development overrides for frontend
  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev

  # Development database with exposed port
  postgres:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=callcenter_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_dev

  # Development redis with exposed port
  redis:
    ports:
      - "6379:6379"
