# Render Blueprint Configuration for AI Callcenter Agent MVP - Minimal Version
# Deploy with: Blueprint Deploy on Render.com

services:
  # Backend API Service - Simple Python Server ONLY
  - type: web
    name: ai-callcenter-backend
    env: python
    plan: free
    region: frankfurt
    runtime: python-3.11
    buildCommand: ""
    healthCheckPath: /health
    autoDeploy: false
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ENVIRONMENT
        value: "production"
      - key: PROJECT_NAME
        value: "AI Callcenter Agent MVP"
      - key: VERSION
        value: "1.0.0"

# Designer: Abdullah Alawiss
