# Docker Compose Configuration
# Designer: Abdullah Alawiss

version: '3.8'

services:
  # Add your services here
  # Example:
  # backend:
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_URL=postgresql://user:password@db:5432/mvp_voice_db
  #   depends_on:
  #     - db
  #
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: mvp_voice_db
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"

volumes:
  postgres_data:
